site_name: AAPS documentation migration
repo_url: https://github.com/peterleimbach/aapsmkdocstest
plugsins:
  - search:
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  features:
    #- navigation.tracking
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    #- navigation.expand
    - navigation.top
    # includes the page toc in the navigation on the left - I don't like it.
    #- toc.integrate 
    #- toc.follow
  #plugins:
  #  - git-revision-date-localized:
  #      enable_creation_date: true
